### ISSUE TITLE
EndOfStreamException in CSceneVehicleCar.Sample

### ISSUE THREAD

**Issue by Thoringer76** [bigbang1112-cz/clip-input#18]
```
Initializing the console...
Using the tool: Clip Input 2
Retrieving possible config options...
Scanning all the command line arguments...

Detected input files:
- 193_Fanakuri0047843_GHOST.Gbx

Using existing ConsoleOptions.yml...

Additional arguments: (none)
Loading config Default.yml...
Config Default.yml saved in standard format.

Parsing 193_Fanakuri0047843_GHOST.Gbx...

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32)
   at System.IO.BinaryReader.ReadSingle()
   at GBX.NET.GameBoxReader.ReadVec3()
   at GBX.NET.Engines.Scene.CSceneVehicleCar.Sample.Read(MemoryStream, GameBoxReader, Int32)
   at GBX.NET.Engines.Game.CGameGhost.Data.ReadSample(Int32, Byte[], Int32[] )
   at GBX.NET.Engines.Game.CGameGhost.Data.Read(GameBoxReader)
   at GBX.NET.Engines.Game.CGameGhost.Data.Read(Stream, Boolean)
   at GBX.NET.Engines.Game.CGameGhost.Data.Parse()
   at GBX.NET.Engines.Game.CGameGhost.get_SampleData()
   at ClipInput.ClipInputTool.GetBlockEndTime(CGameCtnGhost ghost) in D:\a\clip-input\clip-input\ClipInput\ClipInputTool.cs:line 274
   at ClipInput.ClipInputTool.GetGhostsAndEndTime(IEnumerable`1 ghosts, CGameCtnReplayRecord replay) in D:\a\clip-input\clip-input\ClipInput\ClipInputTool.cs:line 87
   at ClipInput.ClipInputTool..ctor(IEnumerable`1 ghosts) in D:\a\clip-input\clip-input\ClipInput\ClipInputTool.cs:line 37
   at ClipInput.ClipInputTool..ctor(CGameCtnGhost ghost) in D:\a\clip-input\clip-input\ClipInput\ClipInputTool.cs:line 30
   at System.RuntimeMethodHandle.InvokeMethod(Object, Void**, Signature, Boolean)
   at System.Reflection.ConstructorInvoker.Invoke(Object, IntPtr*, BindingFlags)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object, IntPtr*, BindingFlags)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags, Binder, Object[], CultureInfo)
   at System.Reflection.ConstructorInfo.Invoke(Object[] )
   at GbxToolAPI.CLI.ToolConstructorPicker.CreateInstances[T](Dictionary`2 inputByType, Boolean singleOutput)+MoveNext()   at GbxToolAPI.CLI.ToolConsole`1.RunCanThrowAsync(String[] args)
   at GbxToolAPI.CLI.ToolConsole`1.RunAsync(String[] args)
Press any key to continue...
```
[193_Fanakuri0047843_GHOST.zip](https://github.com/bigbang1112-cz/clip-input/files/11793137/193_Fanakuri0047843_GHOST.zip)

**Comment by thaumictom** [comment]
This is not a bug of clip-input.

You can use [the online version](https://gbx.bigbang1112.cz/tool/clip-input) or follow [this explanation](https://gbx.bigbang1112.cz/tool/clip-input) to change your config, since you are using TM Turbo.

**Comment by Thoringer76** [comment]
Ah ok, was just wondering because all other TMT replays worked fine previously

**Comment by BigBang1112** [comment]
Thanks for reporting this issue, this seems to lead to GBX.NET, I should've checked TM Turbo replays more intensively.

**Comment by BigBang1112** [comment]
This issue will be addressed later with one of the nearest GBX.NET 2 updates, and this will affect Clip Input once it migrates to v2.

**Comment by BigBang1112** [comment]
Found this issue is related to wrong evaluation of U35_1 and its count in specific terms. This needs more indepth investigation into TM2 samples

**Comment by BigBang1112** [comment]
Finally managed to resolve it through Ghidra MCP, though I won't port it to GBX.NET 1, as I think the transitions will begin soon.
